### ISSUE TITLE
Set default Weather Widget setting to Local

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#19]
Set the default initial setting for the Weather widget to Local so that by default the app shows the user’s current location with dynamic updates.  

![84538094-152E-460E-862B-F4F5FE89B1DE](https://user-images.githubusercontent.com/47233113/54888779-7007df80-4e5d-11e9-80db-df37e225bbfa.png)

**Comment by jcarterOCV** [comment]
This is set to default to the static location as we do not want to bombard a user with multiple permission requests on app open.  Once a user goes to the weather widget settings, uses a form, or opens the weather feature and taps local, it will request this.  With that said, I would request not to change the default here.
(Android defaults to local because when opening the app the first time, they have one permission dialog to ask for this and storage, thus not bombarding the user.)

**Comment by rcmp-randallw** [comment]
We just realized yesterday that the weather/location bar is tied together -- it was our incorrect assumption that the temperature/weather is based on the Widget setting and the middle (Where Am I?) location is separate and independent (it is always giving you your current location) which we want from a 911 perspective (helping the user identify their current location for the call taker).  Thus, our preference would be to default to "Local" at the expense in iOS of prompting the user for multiple permissions (safety over convenience).

**Comment by jcarterOCV** [comment]
This will be updated with build 17
