### ISSUE TITLE
Photos take up too much space, user does not have much real estate to view the text under the screen

### ISSUE THREAD

**Issue by ylin1CoR** [richmondrcmp/mobileapp#28]
Issue: On the Project 529 page, the photo sticks and takes up quite a lot of space on the screen.  The user does not have much real estate on screen to view the text 

**To Reproduce**
1. Go to Crime Prevention
2. Click on 'Project 529
3. Scroll down to view additional text

**Expected behavior**
Allow user to scroll without the picture sticking on the screen

**Smartphone (please complete the following information):**
iphone 7 ios 12.2

 

![Project 529](https://user-images.githubusercontent.com/47400982/55654240-b5090b80-57a5-11e9-968a-3097f204d9ba.jpg)

**Comment by rcmp-randallw** [comment]
This is the way content (images and the page content) are displayed in the app so this is not considered an issue but an implementation.  Page content can be created with inline images but it is not easy or straightforward to create and manage this content (images must be uploaded in a separate section or a third party system and then referenced inline via HTML.

**Comment by rcmp-randallw** [comment]
In addition, text size can be adjusted and while it is not as conventional to have anchored images it is not something that can be easily changed. 

Worth consideration in a future release.

**Comment by rcmp-randallw** [comment]
@ylin1CoR I have updated the Crime Prevention|Auxiliary Constable page to provide an inline image as an example of the ability to create a page where the image doesn't zoom and the image scrolls with the page but this comes at the expense of additional administrative overhead creating the content and doesn't use bandwidth saving thumbnails, however, it does demonstrate that this can be addressed in how the page is created rather than an issue with the mobile app.
