### ISSUE TITLE
Single Push Notification Entry Appearing Twice in Alert History

### ISSUE THREAD

**Issue by rcmp-randallw** [richmondrcmp/mobileapp#47]
We have a single Push Notification showing in the CMS:

![Screen Shot 2019-11-22 at 10 36 48 PM](https://user-images.githubusercontent.com/47233113/69474685-d3456b00-0d78-11ea-8ec7-0fb5a66bae3a.png)

but it appears incorrectly twice in the Alert History on Android:
![Screenshot_20191122-221341_Richmond RCMP](https://user-images.githubusercontent.com/47233113/69474696-f1ab6680-0d78-11ea-88db-3eac1123f437.jpg)

whereas in iOS it appears correctly only once:
![20191123_061356000_iOS](https://user-images.githubusercontent.com/47233113/69474704-07b92700-0d79-11ea-94ed-b690b441b00e.png)

**Comment by jcarterOCV** [comment]
@rcmp-randallw Just updating you on this, our time has been working on this over the last few work days (and very heavily yesterday) and have only been able to replicate one time.  When closing out of the app and coming back in the issue resolved itself.

If we can not find a set way to replicate this issue, we may not be able to resolve this edge case

We talked internally after testing this yesterday and this could be a cache issue that is possible due to the  multiple versions that have been installed over time and cached.  This was just an idea that we had.

**Comment by rcmp-randallw** [comment]
I am running a Samsung S9 with Android 9 and the two Alert entries still appear after uninstalling and reinstalling the app.  

Is there any way to clear the multiple versions cache?

**Comment by cwaldonOCV** [comment]
Samsungs in particular like to hold on to extra data in between installing and uninstalling. In order to fix this, be sure to go in to the Settings of the RCMP app, then click on Access Controls. This will pull up the App info screen. Click on Storage, located under "Usage", then click "Clear cache" followed by "Clear data". A dialog will pop up at the bottom of the screen. Click "OK." 

This should fix the issue, but as for the cause, it seems to have something to do with multiple versions as Josh mentioned above. To give you some more information here, when Android updates your app (or more specifically in this case, AppCenter) it will clear out the cache and on some devices local storage. As I said before, Samsungs run a different (forked) version of Android, and in between installs, Samsung will keep the information stored in Local Storage. In some cases, this is beneficial, but in the interest of troubleshooting, it is not. To disable this functionality, I have changed the parameter in the AndroidManifest.xml "allowBackup" to false. In the future, this problem shouldn't resurface after you follow the aforementioned steps.

What is likely happening is that the Push History from previous versions has persisted when downloading the new information. Sometimes there can be visual bugs, as what I dealt with yesterday, that will occasionally duplicate notifications in the Push History, but it takes a very specific series of steps to replicate this, and is easily rectified by restarting the app or reopening the Push History. 

Please let me know if you ever run into this problem again.

Devices used during testing: Samsung S10+, Google Pixel XL, Google Pixel 2 XL

**Comment by rcmp-randallw** [comment]
@cwaldonOCV That did the trick!  Thank you very much for the insight and detailed instructions.
